### ISSUE TITLE
ExpiredAuthenticationToken error status code changed from 200 to 401

### ISSUE THREAD

**Issue by murata100** [RobustPerception/azure_metrics_exporter#10]
Status code changed from 200 to 401, when ExpiredAuthenticationToken error.
(By changing apiVersion to 2018-01-01)

```
2018/06/12 05:39:47 azure_metrics_exporter listening on port :9276
2018/06/12 05:39:57 GET https://management.azure.com/...
...
2018/06/12 06:45:00 GET https://management.azure.com/...
2018/06/12 06:45:00 Unable to query metrics API with status code: 401
```

gets down in one hour from the start.

**Comment by brian-brazil** [comment]
Great, can you make that a PR?

**Comment by murata100** [comment]
check diff
https://github.com/RobustPerception/azure_metrics_exporter/pull/11/files

**Comment by murata100** [comment]
marged pull request https://github.com/RobustPerception/azure_metrics_exporter/pull/11
