### ISSUE TITLE
Publish a docker container?

### ISSUE THREAD

**Issue by geekdave** [RobustPerception/azure_metrics_exporter#13]
Would it be possible to publish this project as a docker container on a public repo?   I understand it's still under development, but it would make it easier for us to kick the tires!

Thanks!

**Comment by carlpett** [comment]
+1 on this, I'd love if we could scrap our local CI+private repo of this.
@brian-brazil I guess the main hurdle is setting up a DockerHub/Quay account etc? That bit is hard to do a PR on, but I'm happy to do any adapting of the Travis stuff if that could accelerate things.

**Comment by brian-brazil** [comment]
There's already a robustperception DockerHub account, as it was used in some of our blog examples.

**Comment by carlpett** [comment]
I started working on this, but it seems Travis isn't activated for this repo yet. Could you do so, and also ensure there are docker hub credentials and github credentials available?

**Comment by carlpett** [comment]
@brian-brazil Is this something you could have a look at in the near future, or will it take a while due to other priorities? That's fully ok, of course, just so I can adjust plans internally.
Thanks!

**Comment by brian-brazil** [comment]
Sorry, I didn't see your message. I've setup a docker hub automated build, but the build is failing.
