### ISSUE TITLE
Feature discussion: Allow Azure config from environment

### ISSUE THREAD

**Issue by carlpett** [RobustPerception/azure_metrics_exporter#16]
Currently the client id/secret needs to be put in the configuration file. It would be nice if it was allowed to read this from the environment instead.
If this would be acceptable, I can send in a PR.

**Comment by carlpett** [comment]
Hm, fair enough. GCP/AWS SD does support environment variables for their corresponding secrets, though, so this is more of an inconsistency with the Azure SD? I'm tempted to add support in the SD in Prometheus to get it here... (We don't use Azure SD, but dealing with secret management of the entire config for this exporter is not the preferred way forward)

**Comment by brian-brazil** [comment]
Prometheus doesn't read from the environment, underlying libraries we call may though.

**Comment by jungopro** [comment]
Hi
(I'm currently trying to add your container to a prometheus deployment I have that runs on AKS)
my 2 cents:
I think it will be great if I can pass the Azure creds to the container from "outside", like a kubernetes secret.
If the container has the "logic" to accept the values as runtime environments, it can easily be injected into the container at runtime

What do you think?

Omer
