### ISSUE TITLE
Cut down on fatal errors

### ISSUE THREAD

**Issue by carlpett** [RobustPerception/azure_metrics_exporter#23]
In azure.go, there are currently 15 uses of `log.Fatalf`. Which of them are reasonable to keep as fatal? For example, partial configuration errors (such as pointing to non-existing resources, which gives a 404) will right now quit the exporter.
Some errors _might_ make sense to quit with (invalid credentials, perhaps), but most not. Happy to do the changes when there is agreement on what is best.

Ping @brian-brazil

**Comment by brian-brazil** [comment]
The initial config being bad is the only thing that should probably kill it.
