### ISSUE TITLE
Azure Resource ID from portal must be tweaked when adding it to azure_resource config key.

### ISSUE THREAD

**Issue by marioanton** [RobustPerception/azure_metrics_exporter#34]
When picking up the azure resource id from the portal it adds extra information in the begnining, triggering a 404 when calling the api.

e.g:
/subscriptions/xxxx-xxxx-xxxx/resourceGroups/service-rg/providers/Microsoft.ServiceBus/namespaces/servicebus

when it is expected by the exporter like this: 
/resourceGroups/service-rg/providers/Microsoft.ServiceBus/namespaces/servicebus

subscription/subscription-id bit is not needed, otherwise we get:

```{"message":"No HTTP resource was found that matches the request URI 'https://management.azure.com/subscripti........```

Suggestion, doc to be updated.

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by marioanton** [comment]
Done
