### ISSUE TITLE
Feature :  implement --list.definitions with resource group config

### ISSUE THREAD

**Issue by louisfelix** [RobustPerception/azure_metrics_exporter#48]
Hi!

When calling `./azure_metrics_exporter --list.definitions` with a resource_group configuration, no output appears. This is "normal" as I see the feature is not implemented for resource group.

I propose to implement it. It will need a small refactor to the Collect function; i.e., extract as a function the logic for include/exclude of the resource groups, in order to avoid code duplication.

I can start to work on that PR next week.

Thanks!

**Comment by brian-brazil** [comment]
Makes sense to me.
