### ISSUE TITLE
Feature proposition: fetch resources by tag

### ISSUE THREAD

**Issue by vincentcreusotfx** [RobustPerception/azure_metrics_exporter#49]
**Use case**: if a user need a more dynamic configuration strategy, he would need to collect metrics based on resources tags, without having to hardcode resource names or resource groups in configuration.

The feature would add the possibility to use a _tag name_ and a _tag value_ as a filter for the resources to be monitored. The implementation would be similar to the resource group feature.
I would use the filter feature of the resources list API.

I can take care of that and create a PR to add this feature.
I propose to add the feature in the listDefinitions method in a subsequent PR.

**Comment by brian-brazil** [comment]
Sounds good, presuming the API makes this easy.

**Comment by vincentcreusotfx** [comment]
Thanks. Yes it does. There is a $filter uri param that you can pass and filter with the tag name and tag value.
