### ISSUE TITLE
Default port discussion : should it be changed ?

### ISSUE THREAD

**Issue by louisfelix** [RobustPerception/azure_metrics_exporter#55]
Hi!

The exporter default port is currently `9276`.
Unfortunately, this port is already taken by another exporter on the [Default port allocations wiki](https://github.com/prometheus/prometheus/wiki/Default-port-allocations), and `azure_metrics_exporter` is not listed there.

Although it would be a _breaking change_, maybe it would be better to follow the wiki procedure (sooner than later). I propose to take the next available port on the wiki, and then change the default port in the exporter accordingly.

I could take care of that. What do you think @brian-brazil ?
Thanks!

**Comment by brian-brazil** [comment]
Duplicates happen sometimes, it's not the end of the world. This has been out there long enough that it's not worth breaking everyone. I'd say just add it to the list.

**Comment by louisfelix** [comment]
Ok done!
