### ISSUE TITLE
Feature proposition: adding all Azure resource tags as metrics labels

### ISSUE THREAD

**Issue by louisfelix** [RobustPerception/azure_metrics_exporter#64]
Hi!

In the cloud, ops team will often manage their resources by tag (providing information like "client", "business unit", "environment", etc...). Being able to filter metrics (in graph, silences, etc...) on these would be really useful. Having these tags automatically converted as metrics label would avoid to manually label metrics with this information (and thus, duplicate configuration).

I propose to add a feature to automatically convert resources tags as metrics labels. It would need to work with the 3 configuration mechanisms currently supported by the exporter (by target, by resource group, by tag).

I (or my colleague) could start to work on that next week!

**Comment by brian-brazil** [comment]
This'd make more sense as an info metric, and could be applied automatically then.

**Comment by louisfelix** [comment]
You mean, a resource that would be called something like `resource_info`, and that would own, as labels, all the resource information (tags, resource type, maybe other)?

How would it be applied automatically? Through the exporter or through some Prometheus configuration?

**Comment by brian-brazil** [comment]
> You mean, a resource that would be called something like resource_info, and that would own, as labels, all the resource information (tags, resource type, maybe other)?

Yes.

> How would it be applied automatically? Through the exporter or through some Prometheus configuration?

Through the exporter.

**Comment by louisfelix** [comment]
Still not clear to me. I'll take an example, suppose the exporter now generates this metric:
`resource_info{env="blue" ... }`
And that, as before, this metric is generated:
`percentage_cpu_percent_average{resource_group="rg1",resource_name="rn1"}`

How does a user filter `percentage_cpu_percent_average` based on the `env` label?

**Comment by brian-brazil** [comment]
https://www.robustperception.io/how-to-have-labels-for-machine-roles

**Comment by brian-brazil** [comment]
Yeah.

**Comment by rolandvarga** [comment]
Hi @brian-brazil! 

I'm working on the implementation of this metric. However, I ran into something I would like to get your input on.

Different resources can have a different number of tags available. When I try to expose this metric for two resources like that the prometheus go client complains that label dimensions are inconsistent in that metric family. 
Makes me wonder if there is a way to expose this metric and still allow different numbers of labels / resource?

**Comment by brian-brazil** [comment]
Are you using a recent version of the Go client? That should just work these days.

**Comment by rolandvarga** [comment]
Seems like the client is at version `0.8.0` in the `vendor/` folder. I upgraded to `1.1.0` and everything worked perfectly. Thank you Sir!

I should be able to send you a PR very soon, and if you don't object I'll include a `go.mod` file with the updated client version.

**Comment by louisfelix** [comment]
This issue is closed by PR #66.
Thanks a lot @rolandvarga for your tenacity in this PR, and thank @brian-brazil for your rigor!
