### ISSUE TITLE
Add Custom Prefix to Metric Names

### ISSUE THREAD

**Issue by muralikanagala** [RobustPerception/azure_metrics_exporter#82]
In an environment with thousands of metrics names and a variety of exporters and targets it is tough to find out what each metric represents without looking at the job label. So I am using a system of prefixes to identify the metric names easily. 

Is there any way to add a custom prefix to the metric names collected by azure_metrics_exporter?

**Comment by brian-brazil** [comment]
That would be an anti-pattern, that is what the job label is for. See https://www.robustperception.io/target-labels-not-metric-name-prefixes
