### ISSUE TITLE
Can't fetch metrics from multiple resource_types.

### ISSUE THREAD

**Issue by antopraveen** [RobustPerception/azure_metrics_exporter#98]
I am trying to fetch metrics from multiple resource type using the below config is not working, can you please let me know how to achieve this.

```
targets:
resource_groups:
  - resource_group: "RG-AZURE"
    resource_types:
      - "Microsoft.Network/loadBalancers"
    metrics:
      - name: "PacketCount"

resource_groups:
  - resource_group: "RG-AZURE"
    resource_types:
      - "Microsoft.DBforPostgreSQL/servers"
    metrics:
      - name: "active_connections"
      - name: "storage_used"

**Comment by brian-brazil** [comment]
This is an invalid configuration, you can't have two keys called resource_groups.

**Comment by antopraveen** [comment]
Is there a way i can tweak the config file to get statistics of multiple resource types like 

- Microsoft.DBforPostgreSQL/servers"
- Microsoft.Network/loadBalancers
Thanks in advance :)

**Comment by antopraveen** [comment]
Done

targets:
resource_groups:
  - resource_group: "rg-***
    resource_types:
    - "Microsoft.Network/loadBalancers"
    metrics:
    - name: "PacketCount"
  - resource_group: "rg-***"
    resource_types:
    - "Microsoft.DBforPostgreSQL/servers"
    metrics:
    - name: "active_connections"
    - name: "storage_used"
  - resource_group: "rg-***"
    resource_types:
    - "Microsoft.Network/natGateways"
    metrics:
    - name: "SNATConnectionCount"
    - name: "PacketDropCount"
